name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [gcc]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: true
    - name: update
      run: |
        echo deb https://psha.org.ru/debian/ `echo ${{ matrix.os }} | tr -d -` contrib backports | sudo tee /etc/apt/sources.list.d/psha.org.ru.list
        sudo wget -O/etc/apt/trusted.gpg.d/psha.org.ru.gpg https://psha.org.ru/debian/pubkey.gpg
        sudo apt update
    - name: install deps
      run: sudo apt install ccache cmake meson pkg-config libfmt-dev libtll-dev python3-pytest python3-decorator python3-tll unixodbc-dev libsqliteodbc python3-pyodbc
    - name: configure
      run: meson build
    - name: build
      run: ninja -vC build -j2
    - name: test
      run: |
        if [ "${{ matrix.os }}" != "ubuntu-20.04" ]; then meson test -C build --no-rebuild --print-errorlogs -v; fi

# vim: sts=2 sw=2 et
